### ISSUE TITLE
Download fails with RuntimeError: PyPI's XMLRPC API is currently disabled 

### ISSUE THREAD

**Issue by b-schliessmann** [dbaty/Basket#12]
Trying to download packages, the following happens:

```
> basket download pywin32
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\basket-script.py", line 33, in <module>
    sys.exit(load_entry_point('Basket==1.0', 'console_scripts', 'basket')())
  File "C:\Program Files\Python310\lib\site-packages\basket\main.py", line 338, in main
    return basket.cmd_download(argv)
  File "C:\Program Files\Python310\lib\site-packages\basket\main.py", line 220, in cmd_download
    info = self._find_package_name(package)
  File "C:\Program Files\Python310\lib\site-packages\basket\main.py", line 88, in _find_package_name
    for info in self.client.search({'name': query}):
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 1464, in __request
    response = self.__transport.request(
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 1354, in parse_response
    return u.close()
  File "C:\Program Files\Python310\lib\xmlrpc\client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
>
```

I understand that this interface has been disabled intentionally because of DoS-like issues.

Is there any way to use basket now?

**Comment by dbaty** [comment]
Hi. It's been a bit over a year since you asked, sorry for the late response... As you may have guessed, the answer is: no, Basket cannot be used anymore.

I just added a note in the README about that, with a migration guide to ``pip``: https://github.com/dbaty/Basket#readme. Hope it helps! :)
