### ISSUE TITLE
Must access using HTTPS instead of HTTP

### ISSUE THREAD

**Issue by alexandrenorman** [dbaty/Basket#8]
Running `basket download python-nmap` returns me an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/basket", line 9, in <module>
    load_entry_point('Basket==1.0', 'console_scripts', 'basket')()
  File "/usr/local/lib/python3.5/site-packages/basket/main.py", line 338, in main
    return basket.cmd_download(argv)
  File "/usr/local/lib/python3.5/site-packages/basket/main.py", line 220, in cmd_download
    info = self._find_package_name(package)
  File "/usr/local/lib/python3.5/site-packages/basket/main.py", line 88, in _find_package_name
    for info in self.client.search({'name': query}):
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.5/xmlrpc/client.py", line 1167, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
```

with basket packet pulled from pip. It seems outdated as your code has been corrected since.

**Comment by dbaty** [comment]
Indeed I did not make a release yet with the patch you mention (c9fff6d562f3649399b74d4cc62e00041db80cee). Until then, you may install from a Git clone (which you did, according to #9).
